### PR TITLE
6 sassy cleanup. Resolves #6.

### LINKED ISSUE #6: Clean up sassy-ink branches
Figure out which branch is compiles to what is actually being used as geronimo.css on divesite as of last month. I think McKnight made some alterations to a very outdated branch since then, so those will need to be pulled in.

Then delete all the other branches and update the readme with exactly what branch is what.

### PR DESCRIPTION
**Pull request by taylormcknight**
This closes #6  

The output of ink.scss – ink-geronimo.css – now matches the file with the same name on divesite.

**Note:** ink.scss draws from Zurb Foundation partials + our custom code (ink-geronimo.scss)

To test this, I took the css generated by Sassy Ink's ink.scss – ink-geronimo.css – and used it in the place of the ink-geronimo.css on divesite. Below is the resulting newsletter preview.

oct 20 - ibm revenue drops for 14th straight quarter 20160913

### CODE REVIEW

**Comment by elidickinson** [comment]
So I might just reorganize this so that `ink-geronimo.scss` is the main source file you build to create `ink-geronimo.css` for divesite. (Right now you build `ink.scss` which confused me initially)

And then it looks super close. There's some spacing changes but I think there are one or two actual rules different between the css I get building this and the css in divesite so I might just spend a little time and see if I can figure out what's going on there. It'd be great to get this output byte-for-byte identical to the current css.

**Comment by taylormcknight** [comment]
Yep, totally agree. I'll make sure source / output names match.

**Comment by elidickinson** [comment]
I can do it, I actually already did this in another branch

**Comment by taylormcknight** [comment]
Cool. Haven't started yet, so that works great.

**Comment by elidickinson** [comment]
This branch includes some changes from the upstream sassy-ink project that are not already in the production geronimo css. It also appears to be lacking some tweaks to the rules for `img` tags:

screen shot 2016-09-14 at 12 08 26 pm

It's possible we want to include some of these sassy-ink upgrades in out production CSS but I'd really like to avoid making multiple changes at once. 

I have therefore created a new branch here: https://github.com/industrydive/sassy-ink/tree/match_to_production_geronimo

I think building that branch with something like `sass --precision 6 --sourcemap=none scss/ink-geronimo.scss ink-geronimo.css` results in a css file that is functionally equivalent to the one in production.

**Comment by elidickinson** [comment]
@rtmup The questions for you is how much do you care about pulling in the latest changes from the upstream sassy-ink repo? If you just want to be able to make additional edits to the css for new features, I think we doublecheck that `match_to_production_geronimo` is perfect and then I'll force that into master and you can branch off that to add features.

**Comment by taylormcknight** [comment]
@elidickinson I'm going to make sure `match_to_production_geronimo` is good to go, and we'll move forward with that. Currently, it needs the image tweaks (logo doesn't look great on mobile). Will compare code against divesite develop version.

**Comment by taylormcknight** [comment]
@elidickinson The issue with the logo not looking great on mobile is due to the following difference between in the code:

**SASSY:**

```
@media only screen and (max-width: 600px) {
  table[class="body"] img {
    max-width: auto !important;
    max-height: auto !important; }
```

**Production:**

```
@media only screen and (max-width: 600px) {
  table[class="body"] img {
    width: auto !important;
    height: auto !important; }
```

Basically remove "max" from width and height to match production

**Comment by elidickinson** [comment]
Huh, sure you're in the right branch? I see:

```
/*  Media Queries */
@media only screen and (max-width: 600px) {
  table[class="body"] img {
    width: auto !important;
    height: auto !important; }
```

when I build from match_to_production_geronimo

**Comment by taylormcknight** [comment]
**NOTE:** Needed to rebuild CSS from SCSS since CSS was git ignored. Looks good.

**Comment by elidickinson** [comment]
This PR has been resolved by force pushing `match_to_production_geronimo` branch.

```
EliAir:sassy-ink (master)eli$ git reset --hard match_to_production_geronimo
HEAD is now at 8f6fca8 ink-geronimo.scss builds css equivalent to divesite
EliAir:sassy-ink (master)eli$ git push -f industrydive master
Total 0 (delta 0), reused 0 (delta 0)
To github.com:industrydive/sassy-ink.git
 + 68a4628...8f6fca8 master -> master (forced update)
```

**Pull request closed without merging**
